"""Userhistory added

Revision ID: 20321546b1b9
Revises: c3fffee5e9ff
Create Date: 2021-03-21 13:04:07.083314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20321546b1b9'
down_revision = 'c3fffee5e9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    # ### end Alembic commands ###
